export enum AuthActionTypes {
    RESOLVE_AUTH_SUCCESS = 'RESOLVE_AUTH_SUCCESS',
    RESOLVE_AUTH_FAIL = 'RESOLVE_AUTH_FAIL',

    SIGN_IN = 'SIGN_IN',
    SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL = 'SIGN_IN_FAIL',

    SIGN_UP = 'SIGN_UP',
    SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
    SIGN_UP_FAIL = 'SIGN_UP_FAIL',

    CLEAR_ERRORS = 'CLEAR_ERRORS',

    SIGN_OUT = 'SIGN_OUT',
}
