export enum AuthActionTypes {
    // RESOLVE_AUTH
    RESOLVE_AUTH_SUCCESS = 'RESOLVE_AUTH_SUCCESS',
    RESOLVE_AUTH_FAIL = 'RESOLVE_AUTH_FAIL',
    // PRELOAD_DATA
    PRELOAD_DATA = 'PRELOAD_DATA',
    PRELOAD_DATA_SUCCESS = 'PRELOAD_DATA_SUCCESS',
    PRELOAD_DATA_FAIL = 'PRELOAD_DATA_FAIL',
    // SIGN_IN
    SIGN_IN = 'SIGN_IN',
    SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL = 'SIGN_IN_FAIL',
    // SIGN_UP
    SIGN_UP = 'SIGN_UP',
    SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
    SIGN_UP_FAIL = 'SIGN_UP_FAIL',
    // CLEAR_ERRORS
    CLEAR_ERRORS = 'CLEAR_ERRORS',
    // SIGN_OUT
    SIGN_OUT = 'SIGN_OUT',
    // RESET_PASSWORD_REQUEST
    RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS',
    RESET_PASSWORD_REQUEST_FAIL = 'RESET_PASSWORD_REQUEST_FAIL',
}
