export const Color = {
    MainBlack: '#202020',
    ActiveBlue: '#2089dc',
    InactiveGray: '#ADADAD',
    PureWhite: '#FFFFFF',
    SuccessGreen: '#68B752',
    ErrorRed: '#E92E20',
    SolidBorderGray: '#ADADAD',
    PlaceholderGray: '#ADADAD',
    GTMWin: '#EEEEEE',
    GTMLoss: '#FFFFFF',
    RemoveLeagueRed: '#ED5145',
    AddLeagueGreen: '#60D394',
    SubTextGray: '#ADADAD',
    LightBorderGray: '#eee',
    SleeperBackgroundColor: '#2E3336',
    ESPNBackgroundColor: '#DD0000',
    CancelGray: '#ADADAD',
    LightGray: '#ADADAD',
    SuperLightGray: '#F5F6F4',
    SwitchBackground: '#f4f3f4',
    DarkerLightGray: '#949494',
    PointsGray: '#C7C7C7',
};
