export enum LeagueActionTypes {
    FIND_SLEEPER_LEAGUES_FOR_USER = 'FIND_SLEEPER_LEAGUES_FOR_USER',
    FIND_SLEEPER_LEAGUES_FOR_USER_SUCCESS = 'FIND_SLEEPER_LEAGUES_FOR_USER_SUCCESS',
    FIND_SLEEPER_LEAGUES_FOR_USER_FAIL = 'FIND_SLEEPER_LEAGUES_FOR_USER_FAIL',
}
