export enum LeagueActionTypes {
    // FIND_SLEEPER_LEAGUES_FOR_USER
    FIND_SLEEPER_LEAGUES_FOR_USER = 'FIND_SLEEPER_LEAGUES_FOR_USER',
    FIND_SLEEPER_LEAGUES_FOR_USER_SUCCESS = 'FIND_SLEEPER_LEAGUES_FOR_USER_SUCCESS',
    FIND_SLEEPER_LEAGUES_FOR_USER_FAIL = 'FIND_SLEEPER_LEAGUES_FOR_USER_FAIL',
    // ADD_SLEEPER_LEAGUE
    ADD_SLEEPER_LEAGUE = 'ADD_SLEEPER_LEAGUE',
    ADD_SLEEPER_LEAGUE_SUCCESS = 'ADD_SLEEPER_LEAGUE_SUCCESS',
    ADD_SLEEPER_LEAGUE_FAIL = 'ADD_SLEEPER_LEAGUE_FAIL',
    // REMOVE_SLEEPER_LEAGUE
    REMOVE_SLEEPER_LEAGUE = 'REMOVE_SLEEPER_LEAGUE',
    REMOVE_SLEEPER_LEAGUE_SUCCESS = 'REMOVE_SLEEPER_LEAGUE_SUCCESS',
    REMOVE_SLEEPER_LEAGUE_FAIL = 'REMOVE_SLEEPER_LEAGUE_FAIL',
    // STORE_PRELOADED_LEAGUES
    STORE_PRELOADED_LEAGUES = 'STORE_PRELOADED_LEAGUES',
}
